apiVersion: v1
kind: Service
metadata:
  name: mathoperationservice-srv
spec:
  type: NodePort
  selector: 
    app: mathoperationservice
  ports:
    - name: mathoperationservice
      protocol: TCP
      port: 80
      targetPort: 80